version: '3.8'

services:
  postgres:
    container_name: postgres_container
    hostname: psqlhost
    restart: always
    image: postgres:14.1-alpine
    volumes:
      - matchdb-data:/var/lib/postgresql/data
    ports:
      - 15432:5432
    env_file:
      - ./config/.env.db

  api:
    container_name: api_container
    image: "django-demo:dev"
    restart: always
    build:
      target: development_build
      context: ./api
      cache_from:
        - "django-demo:dev"
        - "django-demo:latest"
        - "*"
      args:
        DJANGO_ENV: development
    command: python -Wd manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
      - 3000:3000
    env_file:
      - ./config/.env.api
    depends_on:
      - postgres
    volumes:
      - ./api:/code




  pgadmin:
    image: dpage/pgadmin4:9.0
    restart: unless-stopped
    env_file:
      - ./config/.env.pgadmin
    tty: true
    depends_on:
      - postgres
    ports:
      - 8080:80
    logging:
      driver: none
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json # preconfigured servers/connections   

    links:
      - "postgres:pgsql-server"
volumes:
  matchdb-data:
    driver: local
  pgadmin-data:
    driver: local