# Generated by Django 4.0.2 on 2022-02-13 21:43

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match_Info',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('VI', 'Video'), ('FC2', 'Fightcade2')], max_length=3)),
                ('url', models.URLField()),
                ('p1_char', models.CharField(choices=[('AN', 'Anakaris'), ('AU', 'Aulbath'), ('BI', 'Bishamon'), ('BU', 'Bulleta'), ('DE', 'Demitri'), ('FE', 'Felicia'), ('GA', 'Gallon'), ('JE', 'Jedah'), ('LE', 'Lei-Lei'), ('LI', 'Lilith'), ('MO', 'Morrigan'), ('SA', 'Sasquatch'), ('VI', 'Victor'), ('QB', 'Q-Bee'), ('ZA', 'Zabel')], max_length=2, null=True)),
                ('p2_char', models.CharField(choices=[('AN', 'Anakaris'), ('AU', 'Aulbath'), ('BI', 'Bishamon'), ('BU', 'Bulleta'), ('DE', 'Demitri'), ('FE', 'Felicia'), ('GA', 'Gallon'), ('JE', 'Jedah'), ('LE', 'Lei-Lei'), ('LI', 'Lilith'), ('MO', 'Morrigan'), ('SA', 'Sasquatch'), ('VI', 'Victor'), ('QB', 'Q-Bee'), ('ZA', 'Zabel')], max_length=2, null=True)),
                ('winner', models.CharField(choices=[('AN', 'Anakaris'), ('AU', 'Aulbath'), ('BI', 'Bishamon'), ('BU', 'Bulleta'), ('DE', 'Demitri'), ('FE', 'Felicia'), ('GA', 'Gallon'), ('JE', 'Jedah'), ('LE', 'Lei-Lei'), ('LI', 'Lilith'), ('MO', 'Morrigan'), ('SA', 'Sasquatch'), ('VI', 'Victor'), ('QB', 'Q-Bee'), ('ZA', 'Zabel')], max_length=2, null=True)),
                ('p1_name', models.TextField(default='', max_length=100)),
                ('p2_name', models.TextField(default='', max_length=100)),
                ('uploader', models.TextField(default='', max_length=100)),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('entry_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('entry_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
