# Generated by Django 4.0.2 on 2022-02-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_info',
            name='timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
