# Generated by Django 4.0.2 on 2022-02-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_remove_matchinfo_entry_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchinfo',
            name='date_uploaded',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='p1_char',
            field=models.CharField(choices=[('AN', 'Anakaris'), ('AU', 'Aulbath'), ('BI', 'Bishamon'), ('BU', 'Bulleta'), ('DE', 'Demitri'), ('FE', 'Felicia'), ('GA', 'Gallon'), ('JE', 'Jedah'), ('LE', 'Lei-Lei'), ('LI', 'Lilith'), ('MO', 'Morrigan'), ('SA', 'Sasquatch'), ('VI', 'Victor'), ('QB', 'Q-Bee'), ('ZA', 'Zabel')], default='AN', max_length=2),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='p2_char',
            field=models.CharField(choices=[('AN', 'Anakaris'), ('AU', 'Aulbath'), ('BI', 'Bishamon'), ('BU', 'Bulleta'), ('DE', 'Demitri'), ('FE', 'Felicia'), ('GA', 'Gallon'), ('JE', 'Jedah'), ('LE', 'Lei-Lei'), ('LI', 'Lilith'), ('MO', 'Morrigan'), ('SA', 'Sasquatch'), ('VI', 'Victor'), ('QB', 'Q-Bee'), ('ZA', 'Zabel')], default='VI', max_length=2),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='winning_char',
            field=models.CharField(choices=[('AN', 'Anakaris'), ('AU', 'Aulbath'), ('BI', 'Bishamon'), ('BU', 'Bulleta'), ('DE', 'Demitri'), ('FE', 'Felicia'), ('GA', 'Gallon'), ('JE', 'Jedah'), ('LE', 'Lei-Lei'), ('LI', 'Lilith'), ('MO', 'Morrigan'), ('SA', 'Sasquatch'), ('VI', 'Victor'), ('QB', 'Q-Bee'), ('ZA', 'Zabel')], default='VI', max_length=2),
        ),
    ]
