# Generated by Django 4.0.2 on 2022-02-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_info_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_info',
            name='video_title',
            field=models.TextField(default='', max_length=100),
        ),
    ]
