# Generated by Django 4.0.4 on 2022-04-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchdb_matches', '0002_alter_matchinfo_p1_name_alter_matchinfo_p2_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchinfo',
            name='p1_name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='p2_name',
            field=models.TextField(default='', max_length=100),
        ),
    ]
