# Generated by Django 4.0.2 on 2022-02-17 02:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0007_rename_winner_match_info_winning_char'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Match_Info',
            new_name='MatchInfo',
        ),
    ]
