# Generated by Django 4.0.2 on 2022-02-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_rename_match_info_matchinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchinfo',
            name='entry_created_at',
        ),
        migrations.RemoveField(
            model_name='matchinfo',
            name='entry_updated_at',
        ),
        migrations.AddField(
            model_name='matchinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='matchinfo',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
