# Generated by Django 4.0.2 on 2022-02-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_alter_matchinfo_date_uploaded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchinfo',
            name='winning_char',
            field=models.CharField(choices=[('AN', 'Anakaris'), ('AU', 'Aulbath'), ('BI', 'Bishamon'), ('BU', 'Bulleta'), ('DE', 'Demitri'), ('FE', 'Felicia'), ('GA', 'Gallon'), ('JE', 'Jedah'), ('LE', 'Lei-Lei'), ('LI', 'Lilith'), ('MO', 'Morrigan'), ('SA', 'Sasquatch'), ('VI', 'Victor'), ('QB', 'Q-Bee'), ('ZA', 'Zabel')], max_length=2, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='matchinfo',
            unique_together={('url', 'timestamp')},
        ),
    ]
